### ISSUE TITLE
Wrong home path when launching with Windows

### ISSUE THREAD

**Issue by tranquvis** [bdeneuter/mindstorms-plugin#4]
Hello @bdeneuter,

When I run the gradle task `launch` on Windows I get the following output:
```
[ant:sshexec] cmd : jrun -cp C:\home\lejos\programs\my.jar ...MyMain
[ant:sshexec] Error: Could not find or load main MyMain
```

As you can see, the home path is wrong.

**Comment by bdeneuter** [comment]
Thx for the PR. I merged your PR and published a new version of the plugin (1.2.3)
